const app = document.querySelector('#app');

const initialState = {
  activeView: 'Overview',
  selectedWorkspace: 'trade-expo',
  workspaces: [
    { id: 'trade-expo', name: 'Trade Expo 2026', purpose: 'Exhibition follow-up', sheet: 'Trade Expo Contacts', contacts: 128, campaigns: 3 },
    { id: 'diwali', name: 'Diwali Outreach', purpose: 'Festival wishes', sheet: 'Diwali Contacts', contacts: 84, campaigns: 2 },
    { id: 'partners', name: 'Business Partnerships', purpose: 'Partner outreach', sheet: 'Partner Prospects', contacts: 42, campaigns: 1 },
  ],
  contacts: [
    { id: 1, workspace: 'trade-expo', name: 'Anika Rao', business: 'Lumina Office Systems', role: 'Director', emails: ['anika@lumina.in', 'sales@lumina.in'], phone: '+91 98450 22190', status: 'Ready', selected: true },
    { id: 2, workspace: 'trade-expo', name: 'Arjun Mehta', business: 'Saffron Foods', role: 'Founder', emails: ['arjun@saffronfoods.co'], phone: '+91 98205 44910', status: 'Ready', selected: true },
    { id: 3, workspace: 'trade-expo', name: 'Priya Shah', business: 'Northstar Logistics', role: 'Operations Head', emails: ['connect@northstarlogistics.in'], phone: '+91 99871 63524', status: 'Ready', selected: true },
    { id: 4, workspace: 'trade-expo', name: 'Vikram Iyer', business: 'Meridian Studio', role: 'Managing Partner', emails: ['vikram@meridian.design'], phone: '+91 90041 86371', status: 'Follow up', selected: false },
    { id: 5, workspace: 'diwali', name: 'Neha Jain', business: 'Cedar Retail', role: 'Owner', emails: ['neha@cedarretail.in'], phone: '+91 99100 88119', status: 'Ready', selected: true },
  ],
  templates: [
    { id: 'expo', name: 'Expo follow-up', subject: 'Wonderful meeting you at Trade Expo', body: 'Hello {{contact_name}},\n\nIt was a pleasure meeting you at Trade Expo. I wanted to follow up and share how we can help {{business_name}}.\n\nWould you be open to a short conversation next week?\n\nWarmly,\nMarkoni team', image: 'Expo brochure.png' },
    { id: 'intro', name: 'Warm introduction', subject: 'A quick introduction', body: 'Hello {{contact_name}},\n\nI am reaching out to introduce our team and see if there is a fit to work with {{business_name}}.\n\nBest regards,\nMarkoni team', image: '' },
  ],
  activeTemplate: 'expo',
  scanRows: [],
};

const stored = localStorage.getItem('gather-state');
const state = stored ? { ...initialState, ...JSON.parse(stored) } : initialState;
const save = () => localStorage.setItem('gather-state', JSON.stringify(state));
const workspace = () => state.workspaces.find(item => item.id === state.selectedWorkspace);
const workspaceContacts = () => state.contacts.filter(item => item.workspace === state.selectedWorkspace);
const initials = value => value.split(' ').map(word => word[0]).join('').slice(0, 2);
const escapeHtml = string => String(string).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

function sidebar() {
  const nav = [['Overview','◌'],['Contacts','♙'],['Scan cards','⌁'],['Campaigns','✉'],['Workspaces','▦']];
  return `<aside class="sidebar"><div class="brand"><span class="brand-mark"></span>Gather</div><div class="workspace-card"><div class="eyebrow">Current workspace</div><select class="workspace-select" data-action="switch-workspace">${state.workspaces.map(item => `<option value="${item.id}" ${item.id === state.selectedWorkspace ? 'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></div><nav class="nav">${nav.map(([label,icon]) => `<button data-view="${label}" class="${state.activeView === label ? 'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}</nav><div class="side-footer"><div class="avatar">R</div><div><strong style="display:block;color:var(--ink)">Rounak</strong><span>Workspace owner</span></div></div></aside>`;
}
function topbar() { return `<header class="topbar"><div class="connection"><span class="dot"></span> Gmail & Google Sheets connected</div><div class="top-actions"><button class="button secondary" data-view="Workspaces">Manage workspaces</button><button class="button primary" data-action="new-workspace">+ New workspace</button></div></header>`; }
function head(title, copy, action = '') { return `<div class="view-head"><div><div class="eyebrow">${escapeHtml(workspace().name)}</div><h1>${title}</h1><p>${copy}</p></div>${action}</div>`; }

function overview() {
  const contacts = workspaceContacts();
  return `${head('A calmer way to grow your network.', 'Capture business cards, organise every contact, and send thoughtful follow-ups from one focused workspace.', '<button class="button primary" data-view="Scan cards">Scan visiting cards</button>')}<section class="stats"><div class="stat"><div class="stat-label">Contacts in workspace</div><div class="stat-value">${contacts.length}</div><div class="stat-foot">+12 added this week</div></div><div class="stat"><div class="stat-label">Email addresses</div><div class="stat-value">${contacts.reduce((total,item) => total + item.emails.length, 0)}</div><div class="stat-foot">All ready to reach</div></div><div class="stat"><div class="stat-label">Campaigns sent</div><div class="stat-value">${workspace().campaigns}</div><div class="stat-foot">This workspace</div></div><div class="stat"><div class="stat-label">Awaiting review</div><div class="stat-value">${state.scanRows.length}</div><div class="stat-foot">From current scan</div></div></section><section class="dashboard-grid"><article class="card"><div class="card-head"><div><h2>Recent activity</h2><span class="card-sub">Everything happening in ${escapeHtml(workspace().name)}</span></div><button class="button text" data-view="Contacts">View contacts</button></div><div class="activity"><div class="activity-icon">⌁</div><div><p>12 visiting cards were added to review</p><small>Today · 10:42 AM</small></div></div><div class="activity"><div class="activity-icon">✉</div><div><p>Expo follow-up was sent to 42 contacts</p><small>Yesterday · 4:18 PM</small></div></div><div class="activity"><div class="activity-icon">▦</div><div><p>${escapeHtml(workspace().sheet)} is in sync</p><small>Yesterday · 3:58 PM</small></div></div></article><article class="card"><div class="card-head"><div><h2>Next step</h2><span class="card-sub">A simple way forward</span></div></div><div class="quick-list"><div class="quick-item"><span>Review extracted cards</span><span class="pill peach">${state.scanRows.length || 0} to review</span></div><div class="quick-item"><span>Choose contacts for outreach</span><span class="pill">${contacts.filter(item => item.selected).length} selected</span></div><div class="quick-item"><span>Draft your campaign</span><button class="button text" data-view="Campaigns">Open →</button></div></div></article></section>`;
}

function contactRows(contacts) { return contacts.map(contact => `<tr><td><input class="checkbox" data-select-contact="${contact.id}" type="checkbox" ${contact.selected ? 'checked':''}></td><td><div class="contact-name"><div class="contact-avatar">${initials(contact.name)}</div><div>${escapeHtml(contact.name)}<div class="muted" style="font-weight:400;font-size:11px">${escapeHtml(contact.role)}</div></div></div></td><td><strong>${escapeHtml(contact.business)}</strong></td><td><div class="email-stack">${contact.emails.slice(0,1).map(email => `<span class="email">${escapeHtml(email)}</span>`).join('')}${contact.emails.length > 1 ? `<span class="more-emails">+${contact.emails.length - 1} additional address</span>` : ''}</div></td><td class="muted">${escapeHtml(contact.phone)}</td><td><span class="pill ${contact.status === 'Follow up' ? 'cream':''}">${escapeHtml(contact.status)}</span></td><td><button class="button text" data-action="edit-contact" data-id="${contact.id}">Edit</button></td></tr>`).join(''); }
function contacts() { const list = workspaceContacts(); return `${head('Your contacts', `Every approved card lives here and syncs with ${workspace().sheet}.`, '<div class="top-actions"><button class="button secondary" data-action="import-contacts">Import contacts</button><button class="button primary" data-view="Scan cards">+ Scan cards</button></div>')}<div class="toolbar"><input data-action="search-contacts" class="search" placeholder="Search name, business or email" /><span class="muted" style="font-size:13px">${list.length} contacts · ${list.reduce((sum,item) => sum + item.emails.length, 0)} email addresses</span></div><div class="card table-wrap"><table class="data-table"><thead><tr><th></th><th>Contact</th><th>Business</th><th>Email address</th><th>Phone</th><th>Status</th><th></th></tr></thead><tbody id="contacts-body">${contactRows(list)}</tbody></table></div>`; }

function scanRows() { return state.scanRows.map((row,index) => `<tr class="${row.duplicate ? 'duplicate-row':''}"><td><div class="preview">▣</div></td><td><input class="cell-input" data-scan-field="name" data-scan-index="${index}" value="${escapeHtml(row.name)}" /></td><td><input class="cell-input" data-scan-field="business" data-scan-index="${index}" value="${escapeHtml(row.business)}" /></td><td><input class="cell-input" data-scan-field="emails" data-scan-index="${index}" value="${escapeHtml(row.emails.join(', '))}" /></td><td><input class="cell-input" data-scan-field="phone" data-scan-index="${index}" value="${escapeHtml(row.phone)}" /></td><td>${row.duplicate ? '<span class="flag">Possible duplicate</span>' : '<span class="pill">Ready</span>'}</td><td><button class="button text" data-action="remove-scan" data-index="${index}">Remove</button></td></tr>`).join(''); }
function scanCards() { const rows = state.scanRows.length; return `${head('Scan visiting cards', 'Upload many card images, check the extracted details, then approve them for this workspace.', '<label class="button primary" for="card-upload">+ Add cards<input class="upload-input" id="card-upload" type="file" accept="image/*" multiple></label>')}<div class="scan-layout"><aside class="card scan-info"><div class="eyebrow">How it works</div><h2>Nothing enters your list without a quick check.</h2><p>We will extract every email and phone number we find. You can change names, remove an address, or resolve duplicates before saving.</p><ol class="step-list"><li>Upload card photos</li><li>Review the extracted rows</li><li>Save approved contacts to ${escapeHtml(workspace().sheet)}</li></ol><div class="notice">Connected spreadsheet: <strong>${escapeHtml(workspace().sheet)}</strong></div></aside><section class="card scan-table">${rows ? `<div class="card-head"><div><h2>${rows} cards ready for review</h2><span class="card-sub">One email is sent individually to each approved address.</span></div><button class="button secondary" data-action="add-sample-scan">Add sample</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Card</th><th>Contact</th><th>Business</th><th>Email addresses</th><th>Phone</th><th>Check</th><th></th></tr></thead><tbody>${scanRows()}</tbody></table></div><div class="review-actions"><span class="muted" style="font-size:12px">${state.scanRows.filter(row => row.duplicate).length} possible duplicates need a decision</span><button class="button primary" data-action="approve-scan">Approve & save to spreadsheet</button></div>` : `<div class="empty-drop"><div><div class="drop-illustration">⌁</div><h2>Drop visiting cards here</h2><p>Upload JPG, PNG, or HEIC photos. You can add several cards at once.</p><label class="button primary" for="card-upload-empty">Choose photos<input class="upload-input" id="card-upload-empty" type="file" accept="image/*" multiple></label><button class="button text" data-action="add-sample-scan" style="display:block;margin:8px auto 0">Try sample cards</button></div></div>`}</section></div>`; }

function campaigns() {
  const selected = workspaceContacts().filter(item => item.selected); const template = state.templates.find(item => item.id === state.activeTemplate);
  const first = selected[0] || { name:'there', business:'your business' }; const preview = template.body.replaceAll('{{contact_name}}', first.name).replaceAll('{{business_name}}', first.business);
  return `${head('Create a campaign', 'Use a template you control. Each selected email address receives a private, individual message.', '<button class="button secondary" data-action="new-template">+ New template</button>')}<section class="campaign-layout"><article class="card form-card"><div class="field"><label>Saved template</label><select data-action="template-select">${state.templates.map(item => `<option value="${item.id}" ${item.id === template.id ? 'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></div><div class="field"><label>Campaign name</label><input id="campaign-name" value="${escapeHtml(template.name)} · ${escapeHtml(workspace().name)}" /></div><div class="field"><label>Email subject</label><input id="campaign-subject" value="${escapeHtml(template.subject)}" /></div><div class="field"><label>Message</label><textarea id="campaign-body">${escapeHtml(template.body)}</textarea><small class="muted">Use {{contact_name}} and {{business_name}} to personalise each email.</small></div><div class="field"><label>Image attachment</label><input id="campaign-image" value="${escapeHtml(template.image)}" placeholder="Upload an image or paste its filename" /></div><button class="button secondary" data-action="save-template">Save template changes</button></article><article class="card form-card"><div class="eyebrow">Sending preview</div><div class="recipient-box"><strong>${selected.reduce((total,contact) => total + contact.emails.length, 0)}</strong> individual emails will be sent to <strong>${selected.length}</strong> selected contacts.<div class="muted" style="font-size:11px;margin-top:5px">Multi-address cards receive one private email per address.</div></div><div class="preview-email"><div class="email-top"><strong>To:</strong> ${escapeHtml(first.emails?.[0] || 'contact@example.com')}<br><strong>Subject:</strong> <span id="preview-subject">${escapeHtml(template.subject)}</span></div><div class="email-content" id="preview-body">${escapeHtml(preview)}${template.image ? `<div class="attachment">▧ Attached image: ${escapeHtml(template.image)}</div>` : ''}<div class="signature">Sent individually via the Gmail account connected to this workspace.</div></div></div><div style="display:flex;gap:9px;margin-top:17px"><button class="button secondary" data-action="send-test">Send test to myself</button><button class="button primary" data-action="send-campaign" ${selected.length ? '' : 'disabled'}>Send campaign</button></div><p class="muted" style="font-size:11px;line-height:1.5">The final product will show the recipient list and confirm the send before Gmail delivers messages.</p></article></section>`;
}

function workspaces() { return `${head('Workspaces', 'Keep each occasion, project, or contact group separate. Each workspace has one connected spreadsheet and its own templates and campaign history.', '<button class="button primary" data-action="new-workspace">+ New workspace</button>')}<section class="workspace-grid">${state.workspaces.map(item => `<article class="card workspace-item"><div class="eyebrow">${escapeHtml(item.purpose)}</div><h2>${escapeHtml(item.name)}</h2><p>${item.contacts} contacts · ${item.campaigns} campaigns</p><div class="spreadsheet">▦ ${escapeHtml(item.sheet)}</div><div class="workspace-meta"><button class="button text" data-action="open-workspace" data-id="${item.id}">Open workspace →</button></div></article>`).join('')}</section><article class="card" style="padding:21px;margin-top:20px"><h2 style="margin:0 0 8px">Import between workspaces</h2><p class="muted" style="font-size:13px;margin:0 0 13px">Copy selected contacts to another workspace. Duplicate checking runs against the destination spreadsheet first.</p><button class="button secondary" data-action="import-contacts">Import or copy contacts</button></article>`; }
function currentView() { return ({'Overview':overview, 'Contacts':contacts, 'Scan cards':scanCards, 'Campaigns':campaigns, 'Workspaces':workspaces}[state.activeView] || overview)(); }
function render() { app.innerHTML = `<div class="app-shell">${sidebar()}<main class="main">${topbar()}<div class="content">${currentView()}</div></main></div>`; bindEvents(); }

function showToast(message) { const toast=document.createElement('div');toast.className='toast';toast.textContent=message;document.body.append(toast);setTimeout(()=>{toast.classList.add('hide');setTimeout(()=>toast.remove(),250)},3000); }
function sampleCards() { return [{name:'Karan Bhatia',business:'Orbit Packaging',role:'Sales Director',emails:['karan@orbitpackaging.in','sales@orbitpackaging.in'],phone:'+91 98765 31120',duplicate:false},{name:'Anika Rao',business:'Lumina Office Systems',role:'Director',emails:['anika@lumina.in','hello@lumina.in'],phone:'+91 98450 22190',duplicate:true},{name:'Meera Kapoor',business:'Elara Events',role:'Founder',emails:['meera@elaraevents.com'],phone:'+91 99881 90420',duplicate:false}]; }
function addSampleCards() { state.scanRows = [...state.scanRows, ...sampleCards()];save();render();showToast('Three sample cards are ready for review.'); }
function approveScans() { const ready = state.scanRows.filter(row => !row.duplicate); const existingEmails = new Set(workspaceContacts().flatMap(c => c.emails)); let saved=0; ready.forEach(row=>{const emails=row.emails.map(e=>e.trim().toLowerCase()).filter(e=>e && !existingEmails.has(e));if(emails.length){state.contacts.push({id:Date.now()+saved,workspace:state.selectedWorkspace,name:row.name,business:row.business,role:row.role||'',emails,phone:row.phone,status:'Ready',selected:true});emails.forEach(e=>existingEmails.add(e));saved++;}});state.scanRows=[];save();state.activeView='Contacts';render();showToast(`${saved} contacts saved to ${workspace().sheet}.`); }
function newWorkspace() { modal('Create a workspace', 'A workspace keeps one spreadsheet, its contacts, templates, and campaigns together.', `<div class="field"><label>Workspace name</label><input id="new-ws-name" placeholder="e.g. New Year Outreach" /></div><div class="field"><label>Purpose or occasion</label><input id="new-ws-purpose" placeholder="e.g. Festival wishes" /></div><div class="field"><label>Spreadsheet</label><select id="new-ws-sheet"><option>Create a new Google Sheet</option><option>Connect an existing Google Sheet</option></select></div>`, 'Create workspace', () => {const name=document.querySelector('#new-ws-name').value.trim();if(!name)return showToast('Please give the workspace a name.');const id=`ws-${Date.now()}`;state.workspaces.push({id,name,purpose:document.querySelector('#new-ws-purpose').value.trim()||'New outreach',sheet:`${name} Contacts`,contacts:0,campaigns:0});state.selectedWorkspace=id;state.activeView='Overview';save();closeModal();render();showToast(`${name} workspace created.`);}); }
function modal(title, copy, fields, confirmText, action) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="modal"><section class="modal"><div class="eyebrow">Gather workspace</div><h2>${title}</h2><p>${copy}</p>${fields}<div class="modal-actions"><button class="button secondary" data-action="close-modal">Cancel</button><button class="button primary" data-action="modal-confirm">${confirmText}</button></div></section></div>`);document.querySelector('[data-action="modal-confirm"]').onclick=action;document.querySelector('[data-action="close-modal"]').onclick=closeModal; }
function closeModal(){document.querySelector('#modal')?.remove();}
function importContacts(){const options=state.workspaces.filter(item=>item.id!==state.selectedWorkspace);modal('Import contacts', 'Copy contacts into this workspace. Duplicate email addresses will be skipped automatically.', `<div class="field"><label>Import from workspace</label><select id="import-from">${options.map(w=>`<option value="${w.id}">${escapeHtml(w.name)}</option>`).join('')}</select></div><div class="field"><label>Import method</label><select><option>Copy all contacts</option><option>Import a CSV file</option></select></div>`, 'Import contacts', ()=>{const source=document.querySelector('#import-from').value;let copies=0;const existing=new Set(workspaceContacts().flatMap(c=>c.emails));state.contacts.filter(c=>c.workspace===source).forEach(c=>{const emails=c.emails.filter(e=>!existing.has(e));if(emails.length){state.contacts.push({...c,id:Date.now()+copies,workspace:state.selectedWorkspace,emails});emails.forEach(e=>existing.add(e));copies++;}});save();closeModal();render();showToast(`${copies} contacts copied with duplicate checking.`);});}

function bindEvents() {
  document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => { state.activeView=button.dataset.view;save();render(); }));
  document.querySelector('[data-action="switch-workspace"]')?.addEventListener('change', event => {state.selectedWorkspace=event.target.value;save();render();});
  document.querySelectorAll('[data-action="new-workspace"]').forEach(button=>button.addEventListener('click',newWorkspace));
  document.querySelectorAll('[data-action="open-workspace"]').forEach(button=>button.addEventListener('click',()=>{state.selectedWorkspace=button.dataset.id;state.activeView='Overview';save();render();}));
  document.querySelectorAll('[data-action="add-sample-scan"]').forEach(button=>button.addEventListener('click',addSampleCards));
  document.querySelectorAll('#card-upload,#card-upload-empty').forEach(input=>input?.addEventListener('change', event=>{const files=[...event.target.files];if(!files.length)return;state.scanRows=[...state.scanRows,...files.map((file,index)=>({name:`Contact ${index+1}`,business:'Review business name',role:'',emails:[],phone:'',duplicate:false,file:file.name}))];save();render();showToast(`${files.length} card photo${files.length>1?'s':''} added for extraction.`);}));
  document.querySelector('[data-action="approve-scan"]')?.addEventListener('click',approveScans);
  document.querySelectorAll('[data-action="remove-scan"]').forEach(button=>button.addEventListener('click',()=>{state.scanRows.splice(Number(button.dataset.index),1);save();render();}));
  document.querySelectorAll('[data-scan-field]').forEach(input=>input.addEventListener('change',event=>{const row=state.scanRows[Number(event.target.dataset.scanIndex)],field=event.target.dataset.scanField;row[field]=field==='emails'?event.target.value.split(',').map(s=>s.trim()).filter(Boolean):event.target.value;save();}));
  document.querySelectorAll('[data-select-contact]').forEach(input=>input.addEventListener('change',()=>{const contact=state.contacts.find(c=>String(c.id)===input.dataset.selectContact);contact.selected=input.checked;save();render();}));
  document.querySelector('[data-action="search-contacts"]')?.addEventListener('input',event=>{const term=event.target.value.toLowerCase();document.querySelector('#contacts-body').innerHTML=contactRows(workspaceContacts().filter(c=>[c.name,c.business,...c.emails].join(' ').toLowerCase().includes(term)));bindEvents();});
  document.querySelectorAll('[data-action="edit-contact"]').forEach(button=>button.addEventListener('click',()=>showToast('Contact editing will open here in the next build.')));
  document.querySelectorAll('[data-action="import-contacts"]').forEach(button=>button.addEventListener('click',importContacts));
  document.querySelector('[data-action="template-select"]')?.addEventListener('change',event=>{state.activeTemplate=event.target.value;save();render();});
  document.querySelector('[data-action="save-template"]')?.addEventListener('click',()=>{const template=state.templates.find(t=>t.id===state.activeTemplate);template.subject=document.querySelector('#campaign-subject').value;template.body=document.querySelector('#campaign-body').value;template.image=document.querySelector('#campaign-image').value;save();render();showToast('Template saved for this workspace.');});
  document.querySelector('[data-action="send-test"]')?.addEventListener('click',()=>showToast('Test email queued. Connect Gmail to deliver it.'));
  document.querySelector('[data-action="send-campaign"]')?.addEventListener('click',()=>modal('Send this campaign?', 'Each selected email address will receive an individual message. No addresses will be revealed to other recipients.', `<div class="notice">${workspaceContacts().filter(c=>c.selected).reduce((n,c)=>n+c.emails.length,0)} messages will be sent from the Gmail account connected to ${escapeHtml(workspace().name)}.</div>`, 'Confirm & send', ()=>{workspace().campaigns++;save();closeModal();render();showToast('Campaign queued for delivery.');}));
  document.querySelector('[data-action="new-template"]')?.addEventListener('click',()=>showToast('Template creation is ready for the next implementation pass.'));
}
render();
